const prisma = require('@libs/prisma');

const users = [
  {
    email: 'admin@mail.com',
    username: 'admin',
    password: '$2b$10$IoeomY91UGOgbdZF/KUAReBvMh7OtDBB2ukmkeY3JtpZAsRUxyH3G',
    fullName: 'Mister Admin',
    phone: '081234567890',
    address: 'example admin street',
    gender: 'Male',
    birthdate: new Date('1971-08-14'),
    avatar: 'https://res.cloudinary.com/denyah3ls/image/upload/v1715770859/yn61qsvi38nnr5hj0t16.jpg',
    role: 'admin',
  },
  {
    email: 'user@mail.com',
    username: 'user',
    password: '$2a$12$8vY9Io88MYRjFumzdUv.ZexWv3ssWDqMPpjnmtmuq.uNockOjB0la',
    fullName: 'Mister User',
    phone: '081234567890',
    address: 'example user street',
    gender: 'Male',
    birthdate: new Date('1971-08-14'),
    avatar: 'https://res.cloudinary.com/denyah3ls/image/upload/v1715770859/fk6mep0afnecdthbinp0.jpg',
    role: 'user',
  },
  {
    email: 'mgiottini1@mail.com',
    username: 'mgiottini1',
    password: '$2y$10$k9vKNFWCsyN7pC8psqA4Ney.mIBC8IjakN4vcbPrgXO29JOlZDOV2',
    fullName: 'Marsh Giottini',
    phone: '081111111111',
    address: '9 Forest Dale Circle',
    gender: 'Male',
    birthdate: new Date('1987-10-07'),
    avatar: 'https://robohash.org/eaqueetadipisci.png?size=50x50&set=set1',
    role: 'user',
  },
  {
    email: 'cweakley2@mail.com',
    username: 'cweakley2',
    password: '$2y$10$kBk4SKg8b7CEkhXwlpVrrecQkm8uoEwwJ7vNr0x.rLeSX9kqmTw5.',
    fullName: 'Chaim Weakley',
    phone: '08426712712',
    address: '2478 Loomis Junction',
    gender: 'Male',
    birthdate: new Date('1974-01-13'),
    avatar: 'https://robohash.org/etanimimolestiae.png?size=50x50&set=set1',
    role: 'user',
  },
  {
    email: 'amunnion3@mail.com',
    username: 'amunnion3',
    password: '$2y$10$DVJ5v1VketEqia4OHsgvAeEdr/FKTDeJpdEl5aofY8Fj6Hi/Ul6DC',
    fullName: 'Adrea Munnion',
    phone: '082635121342',
    address: '1045 Hudson Plaza',
    gender: 'Female',
    birthdate: new Date('1975-06-12'),
    avatar: 'https://robohash.org/quosiuresequi.png?size=50x50&set=set1',
    role: 'user',
  },
  {
    email: 'jteacy4@mail.com',
    username: 'jteacy4',
    password: '$2y$10$lmoCYSCAAGAChefTdArzpOtYNwIwDDczQyOIU1FZDZIMrev2dnJpS',
    fullName: 'Jaye Teacy',
    phone: '087682416968',
    address: '0 Waubesa Avenue',
    gender: 'Male',
    birthdate: new Date('1987-02-25'),
    avatar: 'https://robohash.org/voluptasvoluptatemest.png?size=50x50&set=set1',
    role: 'user',
  },
  {
    email: 'hmanby5@mail.com',
    username: 'hmanby5',
    password: '$2y$10$G23IQ.zPcNVG.t6MiWmxcO6.8qaXJOhj9zCqvi4UnAoncM2SRI.yq',
    fullName: 'Hersh Manby',
    phone: '085802542230',
    address: '3354 Vera Circle',
    gender: 'Male',
    birthdate: new Date('2000-07-02'),
    avatar: 'https://robohash.org/aliquamutdelectus.png?size=50x50&set=set1',
    role: 'user',
  },
  {
    email: 'rgentile6@mail.com',
    username: 'rgentile6',
    password: '$2y$10$6E5UvA0e28MgV27O0qqS/O4HmFV5YQojAtP.u8nCiTpnOAFksx7x2',
    fullName: 'Rossy Gentile',
    phone: '081844803288',
    address: '0120 Scott Plaza',
    gender: 'Male',
    birthdate: new Date('1952-06-08'),
    avatar: 'https://robohash.org/autemtotamquidem.png?size=50x50&set=set1',
    role: 'user',
  },
  {
    email: 'rwingrove7@mail.com',
    username: 'rwingrove7',
    password: '$2y$10$LAnxQUADq337HegNo1Ioa.nekeaoSI9XH9vwWPavb/HOiqqWGDaym',
    fullName: 'Rory Wingrove',
    phone: '083142450305',
    address: '0555 Killdeer Hill',
    gender: 'Female',
    birthdate: new Date('1955-02-16'),
    avatar: 'https://robohash.org/quisquamatqueaut.png?size=50x50&set=set1',
    role: 'user',
  },
  {
    email: 'mzamudio8@mail.com',
    username: 'mzamudio8',
    password: '$2y$10$oxsI/xEabhCowD1q9nUwv.vFuakclIuY013l9LEpa3tRBS7xlfgIa',
    fullName: 'Mahmud Zamudio',
    phone: '081609924262',
    address: '33 Delaware Park',
    gender: 'Male',
    birthdate: new Date('1978-12-05'),
    avatar: 'https://robohash.org/quiamaximequae.png?size=50x50&set=set1',
    role: 'user',
  },
  {
    email: 'wcarnson9@mail.com',
    username: 'wcarnson9',
    password: '$2y$10$TL.oln7/GhU2JftlLmziQeqvULk.5uD.9kVwaklxwP./PD/pZV2C6',
    fullName: 'Wendell Carnson',
    phone: '081306326570',
    address: '7526 Wayridge Trail',
    gender: 'Male',
    birthdate: new Date('1958-06-19'),
    avatar: 'https://robohash.org/sitpariatursed.png?size=50x50&set=set1',
    role: 'user',
  },
];

async function seedUsers() {
  try {
    await prisma.user.createMany({
      data: users,
    });
  } catch (e) {
    console.log(e);
  }
}

module.exports = seedUsers;
