const prisma = require('@libs/prisma');

const users = [
  {
    id: 1,
    email: 'mposselow0@slideshare.net',
    username: 'mposselow0',
    password: 'cC8"=6!u',
    fullName: 'Mona Posselow',
    phone: '865-809-2313',
    address: '2 Drewry Parkway',
    gender: 'Female',
    birthdate: new Date('10-4-2023'),
    avatar: 'http://dummyimage.com/153x100.png/5fa2dd/ffffff',
    role: 'Estimator',
  },
  {
    id: 2,
    email: 'cmottram1@friendfeed.com',
    username: 'cmottram1',
    password: 'cT4~.\\#9x+B(Pc)|',
    fullName: 'Claybourne Mottram',
    phone: '235-865-1534',
    address: '259 Kennedy Lane',
    gender: 'Male',
    birthdate: new Date('4-14-2024'),
    avatar: 'http://dummyimage.com/244x100.png/dddddd/000000',
    role: 'Construction Worker',
  },
  {
    id: 3,
    email: 'bnan2@digg.com',
    username: 'bnan2',
    password: 'zY9}pa?n,.`',
    fullName: 'Benito Nan Carrow',
    phone: '397-841-8802',
    address: '1 Transport Center',
    gender: 'Male',
    birthdate: new Date('2-1-2024'),
    avatar: 'http://dummyimage.com/242x100.png/5fa2dd/ffffff',
    role: 'Subcontractor',
  },
  {
    id: 4,
    email: 'jperigeaux3@wiley.com',
    username: 'jperigeaux3',
    password: 'bY7~fzzU7c',
    fullName: 'Jemimah Perigeaux',
    phone: '922-284-2481',
    address: '28386 Rockefeller Pass',
    gender: 'Female',
    birthdate: new Date('6-24-2023'),
    avatar: 'http://dummyimage.com/110x100.png/ff4444/ffffff',
    role: 'Surveyor',
  },
  {
    id: 5,
    email: 'bbraddon4@biblegateway.com',
    username: 'bbraddon4',
    password: 'jB8<S&R.Qs<xF',
    fullName: 'Benita Braddon',
    phone: '405-894-8235',
    address: '614 Golf View Trail',
    gender: 'Female',
    birthdate: new Date('3-13-2024'),
    avatar: 'http://dummyimage.com/163x100.png/5fa2dd/ffffff',
    role: 'Architect',
  },
  {
    id: 6,
    email: 'nruckert5@prweb.com',
    username: 'nruckert5',
    password: 'nM8&g~9V',
    fullName: 'Nichole Ruckert',
    phone: '570-642-7683',
    address: '1363 Nova Lane',
    gender: 'Female',
    birthdate: new Date('5-19-2023'),
    avatar: 'http://dummyimage.com/117x100.png/cc0000/ffffff',
    role: 'Electrician',
  },
  {
    id: 7,
    email: 'bmatyja6@360.cn',
    username: 'bmatyja6',
    password: 'rS3)7qg0~Fmc',
    fullName: 'Beryl Matyja',
    phone: '611-252-9994',
    address: '2276 Charing Cross Court',
    gender: 'Female',
    birthdate: new Date('8-25-2023'),
    avatar: 'http://dummyimage.com/240x100.png/ff4444/ffffff',
    role: 'Supervisor',
  },
  {
    id: 8,
    email: 'brieme7@home.pl',
    username: 'brieme7',
    password: 'jD0)W4+sL$',
    fullName: 'Bendick Rieme',
    phone: '478-650-8794',
    address: '4 Judy Plaza',
    gender: 'Bigender',
    birthdate: new Date('8-14-2023'),
    avatar: 'http://dummyimage.com/196x100.png/cc0000/ffffff',
    role: 'Engineer',
  },
  {
    id: 9,
    email: 'lkingsman8@tumblr.com',
    username: 'lkingsman8',
    password: 'nU2`+&,&VRjW"',
    fullName: 'Lynsey Kingsman',
    phone: '159-380-5861',
    address: '19227 Laurel Trail',
    gender: 'Female',
    birthdate: new Date('3-15-2024'),
    avatar: 'http://dummyimage.com/171x100.png/cc0000/ffffff',
    role: 'Electrician',
  },
  {
    id: 10,
    email: 'ggibke9@ted.com',
    username: 'ggibke9',
    password: 'oQ5$<iQF8~Wr\\',
    fullName: 'Gretta Gibke',
    phone: '726-646-7799',
    address: '7616 Dixon Road',
    gender: 'Female',
    birthdate: new Date('12-29-2023'),
    avatar: 'http://dummyimage.com/213x100.png/cc0000/ffffff',
    role: 'Subcontractor',
  },
];

async function seedUsers() {
  try {
    await prisma.user.createMany({
      data: users,
    });
  } catch (e) {
    console.log(e);
  }
}

module.exports = seedUsers;
