version: "3"

volumes:
  pg_data_bmwarehouse:

services:
  postgres:
    image: postgres:alpine3.20
    container_name: "pg_bmwarehouse"
    environment:
      - POSTGRES_USER=    
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    restart: always
    ports:
      - 5433:5432
    volumes:
      - pg_data_bmwarehouse:/var/lib/postgresql/data
