#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo -e 'PRE-PUSH\n'

# If everything passes... push to remote
echo 'Check for Unit testing'
pnpm test ||
(
  echo 'Unit Testing failed: View the errors above to see why.'
  false;
)


echo '✅✅ test success push to remote ✅✅'