#workflow name
name: "simple workflow pm2 configuration"

#event, trigger action that running our Jobs.
#In this file we trigger pm2-configuration every we push code to repository.
on: [push]
jobs:
  pm2-configuration:
    #runner, This job will be running in runner with Ubuntu Server latest version.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - run: pnpm install pm2@latest -g #install pm2 global
      - run: pm2 -V #check pm2 version
      - run: pm2 list #check pm2 list
      #link to pm monitor 
      - run: pm2 link 1w0ifbbrltc1u70 zlv7gex8d0p1961 
      #running pm2 in mode cluster and --watch set to auto restart if index.js have changes.
      - run: pm2 start index.js --watch -i max