name: Deploy to cloud with Docker image

on:
  push:
    branches:
      - main

jobs:
  #======Deploy to cloud with Docker =====
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        run: |
          docker build -t BMwarehouseAPI .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag your_image_name "${{ secrets.DOCKER_USERNAME }}/BMwarehouseAPI:latest"
          docker push "${{ secrets.DOCKER_USERNAME }}/BMwarehouseAPI:latest"

      # SSH into cloud server and deploy Docker image
      - name: Deploy Docker image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            docker pull "${{ secrets.DOCKER_USERNAME }}/BMwarehouseAPI:latest"
            docker stop bmwarehouse_container || true
            docker rm bmwarehouse_container || true
            docker run -d -p 5000:5000 --name bmwarehouse_container "${{ secrets.DOCKER_USERNAME }}/BMwarehouseAPI:latest"
